### ISSUE TITLE
Describe best practices for testing

### ISSUE THREAD

**Issue by ckunki** [exasol/python-styleguide#16]
Maybe the style guide should name some best practices for (integration) testing?
I found particularly the following things very helpful: 

- [official documentation](https://docs.python.org/3/library/unittest.html) 
- [validate sys.exit()](https://medium.com/python-pandemonium/testing-sys-exit-with-pytest-10c6e5f7726f)
- [simulate command line arguments in sys.argv](https://stackoverflow.com/questions/18668947) 
- **validate content written to stdout and stderr** based on [contextlib.redirect_stdout](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout) and [contextlib.redirect_stderr](https://docs.python.org/3.8/library/contextlib.html#contextlib.redirect_stderr) which are part of the std since 3.4, 3.5
- In case you want to create integration tests for cli applications, consider [prysk](https://github.com/Nicoretti/prysk-reboot)

**Comment by Nicoretti** [comment]
As discussed with @ckunki, this will be closed. A potential other location for this information is being looked for.
